### ISSUE TITLE
Resizing large images

### ISSUE THREAD

**Issue by dullhunk** [UoMCS/newsagent#26]
If the image attached to an article is too big, the email gets a squashed version that doesn't look good

e.g. http://www.cs.manchester.ac.uk/about-us/news/full-article/?articleid=225

looks OK (-ish) on the page, but the newsagent email version has an image that hasn't been resized but only displays part of the image (probably because of the size of the box it's in?)

**Comment by TheWatcher** [comment]
Addressed in commits included up to a6fb6e5171045a06e7ba6752bc88065ace4f31a3  - images are now resized on upload, and limited to 450x450 pixels for article images and 130x63 for lead images. Aspect-ratio aware scaling is employed to enforce the larger size, while scaling and cropping is used for the smaller.
