### ISSUE TITLE
Supply thumbnail images in feed

### ISSUE THREAD

**Issue by pwolstenholme** [UoMCS/newsagent#35]
It would be great if the feed output of newsagent could include a reference to a resized and compressed thumbnail for each attached image.

The thumbnail be used on the CS website wherever lists of news items are displayed, without the risk of a high-resolution image being uploaded to newsagent and then delaying the loading of pages.
 
This could be introduced as part of the image handling work behind #2 and #26.

**Comment by TheWatcher** [comment]
Addressed in commits included up to a6fb6e5171045a06e7ba6752bc88065ace4f31a3 - RSS feeds now include <code>newsagent:image</code> elements that include a <code>type</code> attribute whose value is "thumb" to indicate the URL of the thumbnail image.
